# Generated by Django 3.2.6 on 2022-09-18 03:10

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_saved_words_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saved_words',
            name='definitions',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=150), size=8),
        ),
    ]
